---
dist: trusty
language: ruby
rvm: 2.6.3
install: gem install jekyll html-proofer bundler
script: jekyll build && htmlproofer _site
deploy:
  local_dir: _site
  provider: pages
  skip_cleanup: true
  github_token: ${DEPLOY_GITHUB_TOKEN}
  keep_history: true
  on:
    branch: master

# Magical setting to make ruby build quicker
sudo: false
cache: bundler
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
