---
dist: trusty
language: ruby
rvm: 2.6.3
install: gem install bundler jekyll html-proofer
script: bundle exec jekyll build && bundle exec htmlproofer _site
deploy:
  local_dir: _site
  provider: pages
  skip_cleanup: true
  github_token: ${DEPLOY_GITHUB_TOKEN}
  keep_history: true
  on:
    branch: master
