name: Picnic Technologies
description: A humble milkman standing on the shoulder of giants.

avatar: https://www.picnic.nl/shared-assets/images/public/img-logo@2x.png

footer-links:
  email: 
  facebook: 
  github: PicnicSupermarket
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!

google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://picnic.tech/

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""
githuburl: https://github.com/PicnicSupermarket/

markdown: kramdown
permalink: /:title/

# Jekyll version
version: v1.0.0

sass:
  sass_dir: _scss
  style: :expanded

plugins:
  - jemoji
  - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
