name: picnic.tech
description: A humble milkman standing on the shoulder of giants

avatar: https://picnic.app/nl/shared-assets/images/public/img-logo@2x.png

footer-links:
  email: 
  facebook: 
  github: PicnicSupermarket
  rss:

google_analytics: UA-113533260-1

url: http://picnic.tech/
baseurl: ""
githuburl: https://github.com/PicnicSupermarket/

markdown: kramdown
permalink: /:title/

# Jekyll version
version: v1.0.0

sass:
  sass_dir: _scss
  style: :expanded

plugins:
  - jemoji
  - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
